name: couldai_user_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  image_picker: ^1.0.7
  video_player: ^2.8.1
  flutter_downloader: ^1.11.6
  shared_preferences: ^2.2.2
  file_picker: ^6.1.1

flutter:
  uses-material-design: true